/**
 * TAYLOR (concierge) chapter openers and per-question example placeholders.
 * Sentence case, warm, plain. No em/en dashes or double hyphens.
 */

export const CHAPTER_META: Record<number, { taylor: string; minutes: number }> = {
  1: { taylor: "Let's get the basics down.", minutes: 3 },
  2: { taylor: "In plain words. No pitch deck voice.", minutes: 6 },
  3: { taylor: "The corporate map. Rough is fine.", minutes: 5 },
  4: { taylor: "The humans who make it run.", minutes: 6 },
  5: { taylor: "Where your time actually goes.", minutes: 6 },
  6: { taylor: "How money flows, not what it is.", minutes: 5 },
  7: { taylor: "Where it breaks and where it burns.", minutes: 6 },
  8: { taylor: "What winning looks like to you.", minutes: 5 },
  9: { taylor: "How you want us to talk to you.", minutes: 4 },
  10: { taylor: "The tools you actually touch.", minutes: 5 },
  11: { taylor: "Last three, then you're done.", minutes: 3 },
};

// Miniature example answers, per question number. Kept short and honest.
export const QUESTION_EXAMPLES: Record<number, string> = {
  1: "Jane Rivera. Friends call me JR.",
  2: "jane@company.com, 415 555 0123",
  3: "Rivera Holdings, Rivera Advisory LLC",
  4: "Founder and managing partner",
  5: "My COO, Sam. And my EA, Priya.",
  6: "We help mid market CFOs close their books faster.",
  7: "Boutique CPA firms and family offices. They pick us because we answer the phone.",
  8: "Monthly retainer, plus project fees on M and A work.",
  9: "Growing. Doubled last year, tight this year.",
  10: "Bay Area primary, clients across California and Texas.",
  11: "Started in 2019 after leaving a Big Four practice. First client was a referral from...",
  12: "Rivera Advisory LLC, Delaware, active. Rivera RE Holdings LLC, Nevada, dormant.",
  13: "100 percent of Advisory, 60 percent of RE Holdings.",
  14: "Sam holds 40 percent of RE Holdings.",
  15: "Nothing dissolving. One new LLC in formation for a joint venture.",
  16: "Advisory is the operating co. Holdings owns the office building it leases to Advisory.",
  17: "Sam Chen, COO, runs delivery. Priya Patel, EA, owns my calendar.",
  18: "Attorney: Marcus at Willkie. CPA: our own firm. Banker: Chase private client.",
  19: "Our top 3 clients: Ridge Capital, Anchor CPA, Meridian. Plus our referral partners.",
  20: "My spouse handles bookkeeping part time.",
  21: "One junior associate is coasting. Watching it.",
  22: "Mondays are internal. Tue to Thu are client. Fridays are admin and family.",
  23: "Client onboarding, monthly close review, weekly team standup.",
  24: "A mix of Notion and my head. Not great.",
  25: "Client escalates on Friday afternoon. I clear my Saturday. Not sustainable.",
  26: "Weekly leadership sync, monthly all hands, quarterly board. Kill the Monday sync.",
  27: "Contract renewals. Expense reports.",
  28: "Retainers auto pay on the first. Project invoices go out on completion, net 15.",
  29: "Payroll every other Friday via Gusto. Contractors on 1099, monthly.",
  30: "MRR and cash balance. Weekly, in a spreadsheet.",
  31: "Monthly P and L from our bookkeeper. I read it, no one else does.",
  32: "Every March, before Q1 collections land.",
  33: "Whether to hire a director of ops or keep contracting it.",
  34: "Something falls through the cracks on a client handoff.",
  35: "Approving expense reports. Reviewing draft proposals line by line.",
  36: "All calendar management and client status updates.",
  37: "Follow up emails after prospect calls. Renewals I forgot to flag 60 days out.",
  38: "Whether to take on a partner. Whether to raise prices.",
  39: "Tried an EA agency. Turnover killed it. Tried Monday dot com. No one used it.",
  40: "We are at 3 million ARR, off my calendar, taking real vacations.",
  41: "Sold or handed off. I am on the board, not in the seat.",
  42: "1 Team health. 2 Client retention. 3 Cash. 4 New product line. 5 My marriage.",
  43: "Culture. I will not hire someone I dread seeing on Monday.",
  44: "No cold outbound. No non competes on staff.",
  45: "Time with my kids while they still want it. A house on the coast.",
  46: "Short and blunt. Give me the context only if I ask.",
  47: "Bullets. Numbers when they matter.",
  48: "Directly. Do not soften it.",
  49: "Slack pings with no context. Meetings that could have been emails.",
  50: "Morning brief by 7 am. One end of day nudge only if something is on fire.",
  51: "Do not joke about my kids or my health. Never say we crushed it.",
  52: "Gmail, one work account, one personal. Work is the one that matters.",
  53: "Google Calendar, same work account.",
  54: "Google Drive, plus a Dropbox my CPA still uses.",
  55: "QuickBooks Online. Bookkeeper does the entries.",
  56: "HubSpot, lightly used.",
  57: "Gusto for payroll and benefits.",
  58: "Practice Ignition for proposals and engagement letters.",
  59: "Slack, plus text for urgent.",
  60: "ChatGPT daily for drafting. Claude for longer analysis.",
  61: "Fewer Sunday nights spent worrying about Monday.",
  62: "That I will end up managing the AI more than it manages me.",
  63: "You did not ask about how I spend my weekends. That matters.",
};

export function exampleFor(n: number): string {
  return QUESTION_EXAMPLES[n] || "Rough notes are fine. Your chief will tidy them.";
}
