project_id = "vacpgxxgdfhgvkduljgs"

[functions.process-scheduled-actions]
verify_jwt = false

[functions.process-policy-rules]
verify_jwt = false

[functions.execute-action-server]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.suppression-admin]
verify_jwt = false
