// Featured roles + industries shown as chip strips in DossierIntake.
// Order is locked. "label" is what we render AND what we ship to the edge function
// (the system prompt matches sections in the catalog by case-insensitive contains).

export type FeaturedItem = { label: string; hint?: string };

export const FEATURED_ROLES: FeaturedItem[] = [
  { label: "CFO" },
  { label: "CEO" },
  { label: "COO" },
  { label: "Chief of Staff" },
  { label: "General Counsel" },
  { label: "CMO" },
  { label: "Chief Revenue Officer" },
  { label: "CHRO" },
  { label: "CIO" },
];

export const FEATURED_INDUSTRIES: FeaturedItem[] = [
  { label: "Financial Services" },
  { label: "Technology / SaaS" },
  { label: "Healthcare" },
  { label: "Manufacturing / Industrial" },
  { label: "Professional Services" },
  { label: "Retail / Consumer" },
  { label: "Real Estate" },
  { label: "Energy" },
];

// "Browse all" expansion. Curated, not the full 150/30 — keeps the inline UI manageable
// while still demonstrating breadth. The model accepts any free-text label the user types.
export const ALL_ROLES: string[] = [
  ...FEATURED_ROLES.map((r) => r.label),
  "Chief Strategy Officer",
  "Chief Customer Officer",
  "Chief Product Officer",
  "Chief Data Officer",
  "Chief Risk Officer",
  "Chief Compliance Officer",
  "Chief Sustainability Officer",
  "President",
  "Founder",
  "Board Director",
  "Head of Finance",
  "Head of Operations",
  "Head of Sales",
  "Head of Marketing",
  "Head of People",
  "Head of Engineering",
  "Head of Product",
  "Head of Strategy",
  "Head of Legal",
  "Head of Customer Success",
  "Head of Business Development",
  "Head of Investor Relations",
  "Head of Communications",
  "VP Finance",
  "VP Operations",
  "VP Sales",
  "VP Marketing",
  "VP Engineering",
  "VP Product",
  "Controller",
  "Treasurer",
  "FP&A Lead",
  "Corporate Development Lead",
  "M&A Lead",
  "General Manager",
  "Plant Manager",
  "Portfolio Manager",
  "Managing Director",
  "Practice Lead",
  "Family Office Principal",
  "Private Equity Operator",
  "Venture Partner",
  "Owner-Operator",
];

export const ALL_INDUSTRIES: string[] = [
  ...FEATURED_INDUSTRIES.map((i) => i.label),
  "Commercial & Community Banking",
  "Asset Management",
  "Insurance",
  "Wealth Management",
  "Fintech",
  "Private Equity",
  "Venture Capital",
  "Hedge Funds",
  "Family Office",
  "Healthcare Provider",
  "Health Insurance / Payer",
  "Medical Devices",
  "Biotech / Pharma",
  "Industrial Manufacturing",
  "Construction",
  "Logistics & Transportation",
  "Hospitality",
  "Education",
  "Nonprofit",
  "Government / Public Sector",
  "Media & Entertainment",
  "Telecommunications",
  "Utilities",
  "Agriculture",
];
