
-- 1. Create internal_keys table (RLS enabled, zero policies = no API access)
CREATE TABLE IF NOT EXISTS public.internal_keys (
  name text PRIMARY KEY,
  key_value bytea NOT NULL DEFAULT extensions.gen_random_bytes(32),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.internal_keys ENABLE ROW LEVEL SECURITY;
-- No RLS policies intentionally — table is inaccessible via PostgREST

-- 2. Insert signing key (value auto-generated by DEFAULT, never in SQL text)
INSERT INTO public.internal_keys (name)
VALUES ('cron_auth')
ON CONFLICT DO NOTHING;

-- 3. Replace get_cron_headers() to generate HMAC tokens
CREATE OR REPLACE FUNCTION public.get_cron_headers()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  ts text;
  signing_key bytea;
  token text;
BEGIN
  ts := extract(epoch from now())::bigint::text;
  SELECT key_value INTO signing_key
    FROM internal_keys WHERE name = 'cron_auth';
  token := encode(
    extensions.hmac(ts::bytea, signing_key, 'sha256'),
    'hex'
  );
  RETURN jsonb_build_object(
    'Content-Type', 'application/json',
    'X-Cron-Timestamp', ts,
    'X-Cron-Token', token
  );
END;
$$;

-- 4. Create verify_cron_token() for Edge Functions
CREATE OR REPLACE FUNCTION public.verify_cron_token(
  p_timestamp text, p_token text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  signing_key bytea;
  expected text;
BEGIN
  IF abs(extract(epoch from now()) - p_timestamp::bigint) > 120 THEN
    RETURN false;
  END IF;
  SELECT key_value INTO signing_key
    FROM internal_keys WHERE name = 'cron_auth';
  IF signing_key IS NULL THEN RETURN false; END IF;
  expected := encode(
    extensions.hmac(p_timestamp::bytea, signing_key, 'sha256'),
    'hex'
  );
  RETURN expected = p_token;
END;
$$;
